add_library(GArchive
  PrivateFunctions/GArchive_addColArray.c
  PublicFunctions/GArchive_addCol.c
  PublicFunctions/GArchive_addVal.c
  PublicFunctions/GArchive_checkFileExists.c
  PublicFunctions/GArchive_close.c
  PublicFunctions/GArchive_init.c
  PublicFunctions/GArchive_writeHeader.c
  PublicFunctions/GArchive_writeLine.c
)

target_link_libraries(GArchive
  PRIVATE GUtilities
)
